<?xml version="1.0" encoding="utf-8"?><Database Name="code_nhienlieu" Class="NhienLieuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=103.81.86.72,6869;Initial Catalog=code_nhienlieu;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NhienLieuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ben" Member="Bens">
    <Type Name="Ben">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XiNghiepID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Ben_Kho_TonKho" Member="Kho_TonKhos" ThisKey="ID" OtherKey="BenID" Type="Kho_TonKho" />
      <Association Name="Ben_Pha" Member="Phas" ThisKey="ID" OtherKey="BenID" Type="Pha" />
      <Association Name="Ben_PhieuXuatKho" Member="PhieuXuatKhos" ThisKey="ID" OtherKey="BenXuatID" Type="PhieuXuatKho" />
      <Association Name="XiNghiep_Ben" Member="XiNghiep" ThisKey="XiNghiepID" OtherKey="ID" Type="XiNghiep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XiNghiep" Member="XiNghieps">
    <Type Name="XiNghiep">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenXiNghiep" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MST" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="XiNghiep_Ben" Member="Bens" ThisKey="ID" OtherKey="XiNghiepID" Type="Ben" />
    </Type>
  </Table>
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ngay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ca1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ca2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DaCham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhaID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NguoiChamID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Pha_ChamCong" Member="Pha" ThisKey="PhaID" OtherKey="ID" Type="Pha" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonVi" Member="DonVis">
    <Type Name="DonVi">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDonVi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DonVi_PhieuNhapKho" Member="PhieuNhapKhos" ThisKey="ID" OtherKey="DonViID" Type="PhieuNhapKho" />
    </Type>
  </Table>
  <Table Name="dbo.DonViTinh" Member="DonViTinhs">
    <Type Name="DonViTinh">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDonViTinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenDonViTinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DonViTinh_NhienLieu" Member="NhienLieus" ThisKey="ID" OtherKey="DonViTinhID" Type="NhienLieu" />
    </Type>
  </Table>
  <Table Name="dbo.Kho_TheKho" Member="Kho_TheKhos">
    <Type Name="Kho_TheKho">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NhienLieuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BenID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DienGiai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Nhap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Xuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ton" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaThoiDiem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NhanVienID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhienLieu_Kho_TheKho" Member="NhienLieu" ThisKey="NhienLieuID" OtherKey="ID" Type="NhienLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kho_TonKho" Member="Kho_TonKhos">
    <Type Name="Kho_TonKho">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BenID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NhienLieuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TonKho" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Ben_Kho_TonKho" Member="Ben" ThisKey="BenID" OtherKey="ID" Type="Ben" IsForeignKey="true" />
      <Association Name="NhienLieu_Kho_TonKho" Member="NhienLieu" ThisKey="NhienLieuID" OtherKey="ID" Type="NhienLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhienLieu" Member="NhienLieus">
    <Type Name="NhienLieu">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhienLieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenNhienLieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaBinhQuan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonViTinhID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NhomID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhienLieu_Kho_TheKho" Member="Kho_TheKhos" ThisKey="ID" OtherKey="NhienLieuID" Type="Kho_TheKho" />
      <Association Name="NhienLieu_Kho_TonKho" Member="Kho_TonKhos" ThisKey="ID" OtherKey="NhienLieuID" Type="Kho_TonKho" />
      <Association Name="NhienLieu_NhienLieu_ChiTiet" Member="NhienLieu_ChiTiets" ThisKey="ID" OtherKey="NhienLieuID" Type="NhienLieu_ChiTiet" />
      <Association Name="NhienLieu_PhieuChuyenKho_ChiTiet" Member="PhieuChuyenKho_ChiTiets" ThisKey="ID" OtherKey="NhienLieuID" Type="PhieuChuyenKho_ChiTiet" />
      <Association Name="NhienLieu_PhieuNhapKho_ChiTiet" Member="PhieuNhapKho_ChiTiets" ThisKey="ID" OtherKey="NhienLieuID" Type="PhieuNhapKho_ChiTiet" />
      <Association Name="NhienLieu_PhieuXuatKho_ChiTiet" Member="PhieuXuatKho_ChiTiets" ThisKey="ID" OtherKey="NhienLieuID" Type="PhieuXuatKho_ChiTiet" />
      <Association Name="DonViTinh_NhienLieu" Member="DonViTinh" ThisKey="DonViTinhID" OtherKey="ID" Type="DonViTinh" IsForeignKey="true" />
      <Association Name="NhienLieu_Nhom_NhienLieu" Member="NhienLieu_Nhom" ThisKey="NhomID" OtherKey="ID" Type="NhienLieu_Nhom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhienLieu_ChiTiet" Member="NhienLieu_ChiTiets">
    <Type Name="NhienLieu_ChiTiet">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NhienLieuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TenChiTiet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhienLieu_NhienLieu_ChiTiet" Member="NhienLieu" ThisKey="NhienLieuID" OtherKey="ID" Type="NhienLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhienLieu_Nhom" Member="NhienLieu_Nhoms">
    <Type Name="NhienLieu_Nhom">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NhienLieu_Nhom_NhienLieu" Member="NhienLieus" ThisKey="ID" OtherKey="NhomID" Type="NhienLieu" />
    </Type>
  </Table>
  <Table Name="dbo.Pha" Member="Phas">
    <Type Name="Pha">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPha" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoPhaCu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoHieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BenID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Pha_ChamCong" Member="ChamCongs" ThisKey="ID" OtherKey="PhaID" Type="ChamCong" />
      <Association Name="Pha_Pha_DieuDong" Member="Pha_DieuDongs" ThisKey="ID" OtherKey="PhaID" Type="Pha_DieuDong" />
      <Association Name="Ben_Pha" Member="Ben" ThisKey="BenID" OtherKey="ID" Type="Ben" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuChuyenKho" Member="PhieuChuyenKhos">
    <Type Name="PhieuChuyenKho">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoPhieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CanCu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DoiTuongXuat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ThoiHanXuat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BenChuyenID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BenNhanID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ngay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayLapPhieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhanVienID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="PhieuChuyenKho_PhieuChuyenKho_ChiTiet" Member="PhieuChuyenKho_ChiTiets" ThisKey="ID" OtherKey="PhieuChuyenID" Type="PhieuChuyenKho_ChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuChuyenKho_ChiTiet" Member="PhieuChuyenKho_ChiTiets">
    <Type Name="PhieuChuyenKho_ChiTiet">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhieuChuyenID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NhienLieuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TonKhoChuyen" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TonKhoNhan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuongChuyen" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaXuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="NhienLieu_PhieuChuyenKho_ChiTiet" Member="NhienLieu" ThisKey="NhienLieuID" OtherKey="ID" Type="NhienLieu" IsForeignKey="true" />
      <Association Name="PhieuChuyenKho_PhieuChuyenKho_ChiTiet" Member="PhieuChuyenKho" ThisKey="PhieuChuyenID" OtherKey="ID" Type="PhieuChuyenKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapKho" Member="PhieuNhapKhos">
    <Type Name="PhieuNhapKho">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoPhieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguonNhap" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonViID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HoaDonSo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayLapPhieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhanVienID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="PhieuNhapKho_PhieuNhapKho_ChiTiet" Member="PhieuNhapKho_ChiTiets" ThisKey="ID" OtherKey="PhieuNhapID" Type="PhieuNhapKho_ChiTiet" />
      <Association Name="DonVi_PhieuNhapKho" Member="DonVi" ThisKey="DonViID" OtherKey="ID" Type="DonVi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapKho_ChiTiet" Member="PhieuNhapKho_ChiTiets">
    <Type Name="PhieuNhapKho_ChiTiet">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhieuNhapID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ben" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NhienLieuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BenNhapID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="NhienLieu_PhieuNhapKho_ChiTiet" Member="NhienLieu" ThisKey="NhienLieuID" OtherKey="ID" Type="NhienLieu" IsForeignKey="true" />
      <Association Name="PhieuNhapKho_PhieuNhapKho_ChiTiet" Member="PhieuNhapKho" ThisKey="PhieuNhapID" OtherKey="ID" Type="PhieuNhapKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuatKho" Member="PhieuXuatKhos">
    <Type Name="PhieuXuatKho">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoPhieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CanCu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DoiTuongXuat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ThoiHanXuat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BenXuatID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayLapPhieu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhanVienID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="PhieuXuatKho_PhieuXuatKho_ChiTiet" Member="PhieuXuatKho_ChiTiets" ThisKey="ID" OtherKey="PhieuXuatID" Type="PhieuXuatKho_ChiTiet" />
      <Association Name="Ben_PhieuXuatKho" Member="Ben" ThisKey="BenXuatID" OtherKey="ID" Type="Ben" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuXuatKho_ChiTiet" Member="PhieuXuatKho_ChiTiets">
    <Type Name="PhieuXuatKho_ChiTiet">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhieuXuatID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NhienLieuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TenPha" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TonTruoc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaXuat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="NhienLieu_PhieuXuatKho_ChiTiet" Member="NhienLieu" ThisKey="NhienLieuID" OtherKey="ID" Type="NhienLieu" IsForeignKey="true" />
      <Association Name="PhieuXuatKho_PhieuXuatKho_ChiTiet" Member="PhieuXuatKho" ThisKey="PhieuXuatID" OtherKey="ID" Type="PhieuXuatKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SettingSoPhieu" Member="SettingSoPhieus">
    <Type Name="SettingSoPhieu">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoPhieuNhap" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoPhieuXuat" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NamHienTai" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pha_DieuDong" Member="Pha_DieuDongs">
    <Type Name="Pha_DieuDong">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhaID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BenCuID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BenMoiID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NgayDieuDong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThayDoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Pha_Pha_DieuDong" Member="Pha" ThisKey="PhaID" OtherKey="ID" Type="Pha" IsForeignKey="true" />
    </Type>
  </Table>
</Database>